use schemars::JsonSchema;
use serde::{de::DeserializeOwned, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MethodKind {
    Read,
    Write,
}

pub trait MethodSpec {
    type Input: Serialize + DeserializeOwned + JsonSchema + Clone + Send + 'static;
    type Output: Serialize + JsonSchema + Clone + Send + 'static;

    const RPC_METHOD: &'static str;
}

pub trait RpcMethodMeta: MethodSpec {
    const KIND: MethodKind;
    const SUMMARY: &'static str;
    const DESCRIPTION: &'static str;
    const DEPRECATED: bool;
}

/// Links a read method's params type to its [`MethodSpec`].
///
/// Generated by `read_method_spec!`, this lets a caller dispatch a read by
/// passing its params alone — the spec (and thus the output type) is inferred,
/// so no turbofish or method-name repetition is needed.
pub trait ReadParams: Sized {
    type Spec: MethodSpec<Input = crate::common::ReadRequest<Self>>;
}

/// Links a write method's body type to its [`MethodSpec`].
///
/// Generated by `write_method_spec!`, this lets a caller dispatch a write by
/// passing its body alone — the spec is inferred and the [`WriteRequest`]
/// wrapper is constructed by the caller (e.g. the gateway client).
///
/// [`WriteRequest`]: crate::common::WriteRequest
pub trait WriteBody: Sized {
    type Spec: MethodSpec<
        Input = crate::common::WriteRequest<Self>,
        Output = crate::common::WriteOperationResult,
    >;
}
