mod common;

use common::{setup_ctx, signer_args};
use near_sdk::{json_types::U128, serde_json::json, NearToken};
use near_workspaces::{network::Sandbox, Worker};
use rstest::rstest;
use templar_manager::commands::{recover_nep141::RecoverNep141, storage_deposit::StorageDeposit};
use test_utils::{
    accounts,
    controller::{ft::FtController, storage_management::StorageManagementController},
    worker, ContractController,
};

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[rstest]
#[tokio::test]
async fn storage_deposit(#[future(awt)] worker: Worker<Sandbox>) {
    let ctx = setup_ctx(&worker);
    accounts!(worker, ft_account, user);

    // Deploy a mock FT contract via test-utils.
    let ft = FtController::deploy(ft_account, "Test Token", "TT").await;

    StorageDeposit {
        signer: signer_args(&user),
        contract_id: ft.id().clone(),
        deposit: None,
        registration_only: false,
    }
    .run(&ctx)
    .await
    .unwrap();

    // Verify storage is registered by checking ft_balance_of (should return 0, not error).
    let balance: U128 = ctx
        .near
        .view(ft.id(), "ft_balance_of")
        .args_json(json!({ "account_id": user.id() }))
        .await
        .unwrap()
        .json()
        .unwrap();
    assert_eq!(balance.0, 0);
}

#[rstest]
#[tokio::test]
async fn recover_nep141(
    #[future(awt)] worker: Worker<Sandbox>,
    #[values(true, false)] force: bool,
) {
    let ctx = setup_ctx(&worker);
    accounts!(worker, ft_account, source, beneficiary);

    // Deploy FT and set up accounts.
    let ft = FtController::deploy(ft_account, "Test Token", "TT").await;

    // Register both accounts for storage and mint tokens to source.
    ft.storage_deposit(&source, NearToken::from_millinear(100))
        .await;
    ft.storage_deposit(&beneficiary, NearToken::from_millinear(100))
        .await;
    ft.mint(&source, U128(1_000_000)).await;

    // Verify source has tokens.
    let balance: U128 = ctx
        .near
        .view(ft.id(), "ft_balance_of")
        .args_json(json!({ "account_id": source.id() }))
        .await
        .unwrap()
        .json()
        .unwrap();
    assert_eq!(balance.0, 1_000_000);

    // Recover: transfer tokens to beneficiary and unregister source's storage.
    // Note: the mock FT's `storage_unregister` (generated by the derive macro) is
    // not `#[payable]`, so the unregister step will fail.  The transfer is a
    // separate transaction and should succeed regardless.
    let result = RecoverNep141 {
        signer: signer_args(&source),
        token_id: ft.id().clone(),
        beneficiary_id: beneficiary.id().clone(),
        force,
    }
    .run(&ctx)
    .await;

    // The command errors on storage_unregister, but the transfer already went through.
    assert!(result.is_err());

    // Beneficiary should now have the tokens (transfer succeeded before the error).
    let beneficiary_balance: U128 = ctx
        .near
        .view(ft.id(), "ft_balance_of")
        .args_json(json!({ "account_id": beneficiary.id() }))
        .await
        .unwrap()
        .json()
        .unwrap();
    assert_eq!(beneficiary_balance.0, 1_000_000);
}
