//! Generated reference for every gateway method.
//!
//! The method lists live in the spec crates ([`for_each_read_method!`],
//! [`for_each_write_method!`], [`for_each_oracle_update_method!`]) and are shared
//! with the RPC service's registration, so the registered methods and this
//! reference cannot drift apart. Regenerate `gateway/METHODS.md` with:
//!
//! ```text
//! cargo test -p templar-gateway-catalog regenerate_methods_md -- --ignored
//! ```
//!
//! [`for_each_read_method!`]: templar_gateway_methods_spec::for_each_read_method
//! [`for_each_write_method!`]: templar_gateway_methods_spec::for_each_write_method
//! [`for_each_oracle_update_method!`]: templar_gateway_oracle_updates_spec::for_each_oracle_update_method

use std::fmt::Write as _;

use templar_gateway_types::{
    spec::{MethodKind, RpcMethodMeta},
    MethodSpec,
};

/// Absolute path to the committed method reference (`gateway/METHODS.md`),
/// resolved relative to this crate. The single source of truth for the file
/// location, shared by the generator binary and the staleness test.
pub const METHODS_MD_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../METHODS.md");

/// Metadata for one gateway method, built from its spec's [`RpcMethodMeta`].
pub struct CatalogEntry {
    pub rpc_method: &'static str,
    pub kind: MethodKind,
    pub summary: &'static str,
    pub description: &'static str,
    pub deprecated: bool,
    pub input_type: &'static str,
    pub output_type: &'static str,
}

impl CatalogEntry {
    #[must_use]
    pub fn of<S: RpcMethodMeta>() -> Self {
        Self {
            rpc_method: S::RPC_METHOD,
            kind: S::KIND,
            summary: S::SUMMARY,
            description: S::DESCRIPTION,
            deprecated: S::DEPRECATED,
            input_type: std::any::type_name::<S>(),
            output_type: std::any::type_name::<<S as MethodSpec>::Output>(),
        }
    }

    /// The namespace segment of the RPC method (before the first `.`).
    #[must_use]
    pub fn namespace(&self) -> &'static str {
        self.rpc_method
            .split_once('.')
            .map_or(self.rpc_method, |(namespace, _)| namespace)
    }
}

/// Every gateway method, built from the canonical spec lists.
#[must_use]
pub fn catalog() -> Vec<CatalogEntry> {
    let mut entries = Vec::new();
    macro_rules! push {
        ($spec:ty) => {
            entries.push(CatalogEntry::of::<$spec>());
        };
    }
    templar_gateway_methods_spec::for_each_read_method!(push);
    templar_gateway_methods_spec::for_each_write_method!(push);
    // `op.get` is registered specially in the service (it reads the operation
    // store, not the chain), so it is listed here directly to keep the reference
    // complete. It is the one method handled outside the shared macros.
    push!(templar_gateway_methods_spec::op::Get);
    templar_gateway_oracle_updates_spec::for_each_oracle_update_method!(push);
    entries
}

/// Render the method reference as Markdown (the contents of `gateway/METHODS.md`).
#[must_use]
pub fn render_markdown() -> String {
    let mut entries = catalog();
    entries.sort_by(|a, b| a.rpc_method.cmp(b.rpc_method));

    let namespace_count = {
        let mut namespaces: Vec<&str> = entries.iter().map(CatalogEntry::namespace).collect();
        namespaces.dedup();
        namespaces.len()
    };

    let mut out = String::new();
    let _ = writeln!(out, "# Gateway Method Reference");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "<!-- @generated by `cargo test -p templar-gateway-catalog regenerate_methods_md -- --ignored`; do not edit by hand. -->"
    );
    let _ = writeln!(
        out,
        "<!-- The method lists live in the spec crates' `for_each_*_method!` macros, which the RPC service also expands to register handlers. -->"
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "{} methods across {namespace_count} namespaces.",
        entries.len(),
    );

    let mut current_namespace = "";
    for entry in &entries {
        if entry.namespace() != current_namespace {
            current_namespace = entry.namespace();
            let _ = writeln!(out);
            let _ = writeln!(out, "## `{current_namespace}`");
            let _ = writeln!(out);
            let _ = writeln!(out, "| Method | Kind | Input → Output | Summary |");
            let _ = writeln!(out, "|---|---|---|---|");
        }
        let kind = match entry.kind {
            MethodKind::Read => "read",
            MethodKind::Write => "write",
        };
        let summary = if entry.deprecated {
            format!("{} _(deprecated)_", entry.summary)
        } else {
            entry.summary.to_owned()
        };
        let _ = writeln!(
            out,
            "| `{}` | {kind} | `{}` → `{}` | {summary} |",
            entry.rpc_method,
            short_type(entry.input_type),
            short_type(entry.output_type),
        );
    }
    out
}

/// Strip module paths from a `type_name`, keeping the leaf of every path segment
/// including those inside generics (e.g.
/// `core::option::Option<templar_common::supply::SupplyPosition>` →
/// `Option<SupplyPosition>`).
fn short_type(full: &str) -> String {
    let mut out = String::new();
    let mut token = String::new();
    for ch in full.chars() {
        if ch.is_alphanumeric() || ch == '_' || ch == ':' {
            token.push(ch);
        } else {
            out.push_str(token.rsplit("::").next().unwrap_or(token.as_str()));
            token.clear();
            out.push(ch);
        }
    }
    out.push_str(token.rsplit("::").next().unwrap_or(token.as_str()));
    out
}

#[cfg(test)]
mod tests {
    /// The committed `gateway/METHODS.md` must match freshly generated output.
    /// If this fails, regenerate it with the ignored `regenerate_methods_md`
    /// test below.
    #[test]
    fn methods_md_is_up_to_date() {
        let generated = super::render_markdown();
        let committed = std::fs::read_to_string(super::METHODS_MD_PATH).unwrap_or_default();
        assert_eq!(
            generated, committed,
            "gateway/METHODS.md is out of date; regenerate with \
             `cargo test -p templar-gateway-catalog regenerate_methods_md -- --ignored`",
        );
    }

    /// Write the generated reference to `gateway/METHODS.md`. Ignored by default
    /// (it mutates the source tree); run it to regenerate after changing methods:
    /// `cargo test -p templar-gateway-catalog regenerate_methods_md -- --ignored`.
    #[test]
    #[ignore = "regenerates gateway/METHODS.md; run explicitly with --ignored"]
    fn regenerate_methods_md() -> std::io::Result<()> {
        std::fs::write(super::METHODS_MD_PATH, super::render_markdown())
    }

    /// Sanity check that the canonical lists actually collected the methods.
    #[test]
    fn catalog_is_populated() {
        assert!(
            super::catalog().len() > 40,
            "expected the catalog to collect every gateway method",
        );
    }
}
