//! Chain-agnostic restrictions (gates) for vault access control.
//!
//! Portable across NEAR and Soroban.

use alloc::collections::BTreeSet;

#[cfg(feature = "borsh")]
use borsh::{BorshDeserialize, BorshSerialize};
use derive_more::IsVariant;
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

use crate::types::Address;

/// Restrictions that can be applied to the vault.
///
/// Supports Pausing, Whitelist, and Blacklist functionality.
#[cfg_attr(feature = "borsh", derive(BorshSerialize, BorshDeserialize))]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[derive(Debug, Clone, PartialEq, Eq, IsVariant)]
pub enum Restrictions {
    /// Vault is paused - all operations blocked.
    Paused,
    /// Blacklist - specified actors are blocked.
    BlackList(BTreeSet<Address>),
    /// Whitelist - only specified actors are allowed.
    WhiteList(BTreeSet<Address>),
}

impl Restrictions {
    /// Check if the given actor is restricted.
    ///
    /// Returns `Some(restriction)` if blocked, `None` if allowed.
    ///
    /// # Arguments
    /// * `actor_id` - The actor to check.
    /// * `self_id` - The vault's own identity (whitelist allows self by default).
    pub fn is_restricted(&self, actor_id: &Address, self_id: &Address) -> Option<Restrictions> {
        match self {
            Restrictions::Paused => Some(Restrictions::Paused),
            Restrictions::BlackList(blacklist) => {
                if blacklist.contains(actor_id) {
                    Some(Restrictions::BlackList(blacklist.clone()))
                } else {
                    None
                }
            }
            Restrictions::WhiteList(whitelist) => {
                if whitelist.contains(actor_id) || actor_id == self_id {
                    None
                } else {
                    Some(Restrictions::WhiteList(whitelist.clone()))
                }
            }
        }
    }

    // Note: is_paused(), is_black_list(), is_white_list() are auto-generated by derive_more::IsVariant
}

#[cfg(test)]
mod tests {
    use super::*;

    fn addr(tag: u8) -> Address {
        [tag; 32]
    }

    #[test]
    fn test_paused_blocks_everyone() {
        let r = Restrictions::Paused;
        let actor = addr(1);
        let self_id = addr(2);
        assert!(r.is_restricted(&actor, &self_id).is_some());
        assert!(r.is_restricted(&self_id, &self_id).is_some());
    }

    #[test]
    fn test_blacklist_blocks_listed() {
        let mut blacklist = BTreeSet::new();
        blacklist.insert(addr(1));
        let r = Restrictions::BlackList(blacklist);

        let self_id = addr(2);
        assert!(r.is_restricted(&addr(1), &self_id).is_some());
        assert!(r.is_restricted(&addr(3), &self_id).is_none());
    }

    #[test]
    fn test_whitelist_allows_listed_and_self() {
        let mut whitelist = BTreeSet::new();
        whitelist.insert(addr(1));
        let r = Restrictions::WhiteList(whitelist);

        let self_id = addr(2);
        assert!(r.is_restricted(&addr(1), &self_id).is_none());
        assert!(r.is_restricted(&self_id, &self_id).is_none());
        assert!(r.is_restricted(&addr(3), &self_id).is_some());
    }
}
