extends = [
    "../profiles/v1.toml",
    "../profiles/v1-collateral-ibtc.toml",
    "../profiles/v1-borrow-iethusdc.toml",
]

name = "ibtc-iethusdc-1"


[collateral]
asset = "nep245:intents.near:nep141:btc.omft.near"
decimals = 8

[borrow]
asset = "nep245:intents.near:nep141:eth-0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48.omft.near"
decimals = 6

[market]
interest_rate_strategy = { Piecewise = { base = "0", optimal = "0.9", rate_1 = "0.0888888888888888888888888888888888889", rate_2 = "2.4" } }
mcr_maintenance = "1.25"
mcr_liquidation = "1.2"
maximum_usage_ratio = "0.99"
liquidation_maximum_spread = "0.08"
price_maximum_age = "60s"
borrow_range = { minimum = "1 atom" }
supply_range = { minimum = "0.04 tokens" }
supply_withdrawal_range = { minimum = "0.04 tokens" }
