extends = ["../profiles/v1-mainnet.toml", "../profiles/irs-stable.toml"]

name = "izec-ixlmusdc"

[collateral]
asset = "nep245:intents.near:nep141:zec.omft.near"
decimals = 8
aggregator = "median_low"
min_sources = 1
sources = [
    { kind = "pyth", oracle = "pyth-oracle.near", price_id = "be9b59d178f0d6a97ab4c343bff2aa69caa1eaae3e9048a65788c529b125bb24", weight = 8 },
    { kind = "red_stone", oracle = "redstone-adapter.v1.tmplr.near", price_id = "ZEC", weight = 2 },
]

[borrow]
asset = "nep245:intents.near:nep245:v2_1.omni.hot.tg:1100_111bzQBB65GxAPAVoxqmMcgYo5oS3txhqs1Uh1cgahKQUeTUq1TJu"
decimals = 7
aggregator = "median_low"
min_sources = 1
sources = [
    { kind = "pyth", oracle = "pyth-oracle.near", price_id = "eaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a", weight = 8 },
    { kind = "red_stone", oracle = "redstone-adapter.v1.tmplr.near", price_id = "USDC", weight = 2 },
]

[market]
mcr_maintenance = "1.66666666666666666666666666666666666667"
mcr_liquidation = "1.53846153846153846153846153846153846154"
maximum_usage_ratio = "0.99"
liquidation_maximum_spread = "0.1"
borrow_range = { minimum = "1" }
supply_range = { minimum = "400000" }
supply_withdrawal_range = { minimum = "400000" }
