//! Chain-agnostic restrictions (gates) for vault access control.
//!
//! Portable across NEAR and Soroban.

use alloc::collections::BTreeSet;

#[cfg(feature = "borsh")]
use borsh::{BorshDeserialize, BorshSerialize};
use derive_more::IsVariant;
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

use crate::types::Address;

/// Lightweight tag indicating why an actor was restricted.
///
/// Unlike [`Restrictions`], this does not carry the full BTreeSet, avoiding
/// allocations on every auth-failure path.
#[cfg_attr(not(target_arch = "wasm32"), derive(Debug))]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum RestrictionKind {
    /// Vault is paused.
    Paused,
    /// Actor appears on the blacklist.
    Blacklisted,
    /// Actor is not on the whitelist.
    NotWhitelisted,
}

/// Restrictions that can be applied to the vault.
///
/// Supports Pausing, Whitelist, and Blacklist functionality.
#[cfg_attr(feature = "borsh", derive(BorshSerialize, BorshDeserialize))]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[cfg_attr(not(target_arch = "wasm32"), derive(Debug))]
#[derive(Clone, PartialEq, Eq, IsVariant)]
pub enum Restrictions {
    /// Vault is paused - all operations blocked.
    Paused,
    /// Blacklist - specified actors are blocked.
    #[cfg_attr(feature = "serde", serde(rename = "BlackList"))]
    Blacklist(BTreeSet<Address>),
    /// Whitelist - only specified actors are allowed.
    #[cfg_attr(feature = "serde", serde(rename = "WhiteList"))]
    Whitelist(BTreeSet<Address>),
}

impl core::fmt::Display for RestrictionKind {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Paused => f.write_str("Paused"),
            Self::Blacklisted => f.write_str("Blacklisted"),
            Self::NotWhitelisted => f.write_str("NotWhitelisted"),
        }
    }
}

impl Restrictions {
    /// Check if the given actor is restricted.
    ///
    /// Returns `Some(kind)` if blocked, `None` if allowed.
    /// The returned [`RestrictionKind`] is a lightweight tag — no allocations.
    ///
    /// # Arguments
    /// * `actor_id` - The actor to check.
    /// * `self_id` - The vault's own identity (whitelist allows self by default).
    pub fn is_restricted(&self, actor_id: &Address, self_id: &Address) -> Option<RestrictionKind> {
        match self {
            Restrictions::Paused => Some(RestrictionKind::Paused),
            Restrictions::Blacklist(blacklist) => {
                if blacklist.contains(actor_id) {
                    Some(RestrictionKind::Blacklisted)
                } else {
                    None
                }
            }
            Restrictions::Whitelist(whitelist) => {
                if whitelist.contains(actor_id) || actor_id == self_id {
                    None
                } else {
                    Some(RestrictionKind::NotWhitelisted)
                }
            }
        }
    }

    // Note: is_paused(), is_blacklist(), is_whitelist() are auto-generated by derive_more::IsVariant
}

#[cfg(test)]
mod tests;
