//! Chain-agnostic restrictions (gates) for vault access control.
//!
//! Portable across NEAR and Soroban.

#[cfg(feature = "borsh-schema")]
use alloc::string::ToString;
use alloc::vec::Vec;
#[cfg(feature = "schemars")]
use alloc::{borrow::ToOwned, boxed::Box, vec};

use derive_more::IsVariant;

use crate::types::Address;

/// Lightweight tag indicating why an actor was restricted.
///
#[templar_vault_macros::vault_derive(borsh_schema, schemars)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum RestrictionKind {
    /// Vault is paused.
    Paused,
    /// Actor appears on the blacklist.
    Blacklisted,
    /// Actor is not on the whitelist.
    NotWhitelisted,
}

/// Restrictions that can be applied to the vault.
///
/// Supports Pausing, Whitelist, and Blacklist functionality.
#[templar_vault_macros::vault_derive(borsh, borsh_schema, postcard, schemars, serde)]
#[derive(Clone, PartialEq, Eq, IsVariant)]
pub enum Restrictions {
    /// Vault is paused - all operations blocked.
    Paused,
    /// Blacklist - specified actors are blocked.
    #[cfg_attr(feature = "serde", serde(rename = "BlackList"))]
    Blacklist(Vec<Address>),
    /// Whitelist - only specified actors are allowed.
    #[cfg_attr(feature = "serde", serde(rename = "WhiteList"))]
    Whitelist(Vec<Address>),
}

impl Restrictions {
    #[inline]
    fn normalize_addresses(addresses: &mut Vec<Address>) {
        addresses.sort_unstable();
        addresses.dedup();
    }

    #[must_use]
    pub fn normalized(mut self) -> Self {
        match &mut self {
            Restrictions::Blacklist(addresses) | Restrictions::Whitelist(addresses) => {
                Self::normalize_addresses(addresses);
            }
            Restrictions::Paused => {}
        }
        self
    }

    #[inline]
    fn contains_address(addresses: &[Address], actor_id: &Address) -> bool {
        if addresses.is_sorted() {
            addresses.binary_search(actor_id).is_ok()
        } else {
            addresses.iter().any(|addr| addr == actor_id)
        }
    }

    /// Check if the given actor is restricted.
    ///
    /// Returns `Some(kind)` if blocked, `None` if allowed.
    /// The returned [`RestrictionKind`] is a lightweight tag — no allocations.
    ///
    /// # Arguments
    /// * `actor_id` - The actor to check.
    /// * `self_id` - The vault's own identity (whitelist allows self by default).
    pub fn is_restricted(&self, actor_id: &Address, self_id: &Address) -> Option<RestrictionKind> {
        match self {
            Restrictions::Paused => Some(RestrictionKind::Paused),
            Restrictions::Blacklist(blacklist) => {
                if Self::contains_address(blacklist, actor_id) {
                    Some(RestrictionKind::Blacklisted)
                } else {
                    None
                }
            }
            Restrictions::Whitelist(whitelist) => {
                if Self::contains_address(whitelist, actor_id) || actor_id == self_id {
                    None
                } else {
                    Some(RestrictionKind::NotWhitelisted)
                }
            }
        }
    }

    // Note: is_paused(), is_blacklist(), is_whitelist() are auto-generated by derive_more::IsVariant
}

#[cfg(test)]
mod tests;
