//! Chain-agnostic restrictions (gates) for vault access control.
//!
//! Portable across NEAR and Soroban.

#[cfg(feature = "borsh-schema")]
use alloc::collections::BTreeMap;
#[cfg(any(feature = "borsh-schema", feature = "schemars"))]
use alloc::string::{String, ToString};
use alloc::vec::Vec;
#[cfg(feature = "schemars")]
use alloc::{borrow::ToOwned, boxed::Box, vec};

use crate::types::Address;
#[cfg(feature = "borsh")]
use borsh::{BorshDeserialize, BorshSerialize};
use derive_more::IsVariant;
#[cfg(feature = "schemars")]
use schemars::{gen::SchemaGenerator, schema::Schema, JsonSchema};

fn normalize_addresses(mut addresses: Vec<Address>) -> Vec<Address> {
    let mut deduped = Vec::with_capacity(addresses.len());
    for address in addresses.drain(..) {
        if !deduped.contains(&address) {
            deduped.push(address);
        }
    }
    deduped
}

/// Lightweight tag indicating why an actor was restricted.
///
#[templar_vault_macros::vault_derive(borsh_schema, schemars)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum RestrictionKind {
    /// Vault is paused.
    Paused,
    /// Actor appears on the blacklist.
    Blacklisted,
    /// Actor is not on the whitelist.
    NotWhitelisted,
}

#[templar_vault_macros::vault_derive(borsh, borsh_schema, postcard, schemars, serde)]
#[derive(Clone, PartialEq, Eq, IsVariant)]
pub enum RestrictionMode {
    /// Blacklist - specified actors are blocked.
    #[cfg_attr(feature = "serde", serde(rename = "BlackList"))]
    Blacklist(Vec<Address>),
    /// Whitelist - only specified actors are allowed.
    #[cfg_attr(feature = "serde", serde(rename = "WhiteList"))]
    Whitelist(Vec<Address>),
}

pub type Restrictions = RestrictionMode;

impl RestrictionMode {
    #[must_use]
    pub fn blacklist(addresses: Vec<Address>) -> Self {
        Self::Blacklist(normalize_addresses(addresses))
    }

    #[must_use]
    pub fn whitelist(addresses: Vec<Address>) -> Self {
        Self::Whitelist(normalize_addresses(addresses))
    }

    #[must_use]
    pub fn normalized(self) -> Self {
        match self {
            Self::Blacklist(addresses) => Self::Blacklist(normalize_addresses(addresses)),
            Self::Whitelist(addresses) => Self::Whitelist(normalize_addresses(addresses)),
        }
    }

    #[must_use]
    pub fn addresses(&self) -> &[Address] {
        match self {
            Self::Blacklist(addresses) | Self::Whitelist(addresses) => addresses,
        }
    }

    /// Check if the given actor is restricted.
    ///
    /// Returns `Some(kind)` if blocked, `None` if allowed.
    /// The returned [`RestrictionKind`] is a lightweight tag — no allocations.
    ///
    /// # Arguments
    /// * `actor_id` - The actor to check.
    pub fn is_restricted(&self, actor_id: &Address) -> Option<RestrictionKind> {
        match self {
            Self::Blacklist(blacklist) => {
                if blacklist.contains(actor_id) {
                    Some(RestrictionKind::Blacklisted)
                } else {
                    None
                }
            }
            Self::Whitelist(whitelist) => {
                if whitelist.contains(actor_id) {
                    None
                } else {
                    Some(RestrictionKind::NotWhitelisted)
                }
            }
        }
    }

    #[must_use]
    pub fn is_restricted_allowing_self(
        &self,
        actor_id: &Address,
        self_id: &Address,
    ) -> Option<RestrictionKind> {
        match self {
            Self::Whitelist(_) if actor_id == self_id => None,
            _ => self.is_restricted(actor_id),
        }
    }

    // Note: is_paused(), is_blacklist(), is_whitelist() are auto-generated by derive_more::IsVariant
}

#[cfg(test)]
mod tests;
