#!/usr/bin/env python3
"""Render the release catalog tables in docs/src/release-log.md.

Usage: gen-release-log.py [--check | --stdout]

Reads every row of `contract/artifacts/releases/*.tsv` (one released WASM per
row: artifact, version, release tag, asset, SHA-256, byte length), joins it
with the hand-maintained annotations in `script/docs/release-annotations.toml`,
and writes the tables between the `BEGIN GENERATED` / `END GENERATED` markers
of the page. Prose outside the markers is hand-written and left alone.

`--check` regenerates in memory and exits 1 with a diff if the page is stale;
`--stdout` prints the block instead of writing. The output is a pure function
of the inputs: no timestamps, no commit hashes.
"""

import argparse
import difflib
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RELEASES = ROOT / "contract" / "artifacts" / "releases"
ANNOTATIONS = Path(__file__).resolve().parent / "release-annotations.toml"
PAGE = ROOT / "docs" / "src" / "release-log.md"

BEGIN = "<!-- BEGIN GENERATED: release-log (script/docs/gen-release-log.py) -->"
END = "<!-- END GENERATED: release-log -->"

RELEASE_URL = "https://github.com/Templar-Protocol/contracts/releases/tag"
INPUT_NEEDED = "**Input needed**"

# Where each artifact's crate lives today, for the "source version" column.
# Mirrors `ArtifactId::metadata().source_path` in `contract/artifacts/src/ids.rs`.
CRATES = {
    "market": "contract/market",
    "registry": "contract/registry",
    "proxy-oracle": "contract/proxy-oracle/near/contract",
    "proxy-governance": "contract/proxy-oracle/near/governance-contract",
    "lst-oracle": "contract/proxy-oracle/near/lst-contract",
    "redstone-adapter": "contract/redstone-adapter",
    "pyth-lazer-adapter": "contract/pyth-lazer/contract",
    "universal-account": "contract/universal-account",
    "vault": "contract/vault/near",
    "patch-state": "contract/patch-state",
}

DESCRIPTIONS = {
    "market": "Lending market (one collateral asset, one borrow asset)",
    "registry": "Registry that deploys markets and proxy oracles",
    "proxy-oracle": "Proxy oracle (NEAR runtime)",
    "proxy-governance": "Proxy oracle governance (timelocked owner)",
    "lst-oracle": "Liquid-staking-token oracle adapter",
    "redstone-adapter": "RedStone price adapter",
    "pyth-lazer-adapter": "Pyth Lazer price adapter",
    "universal-account": "Universal account (multi-chain signing)",
    "vault": "NEAR vault runtime",
    "patch-state": "Storage-patch helper contract",
}


def semver(text):
    return tuple(int(p) for p in text.split("."))


def load_rows():
    rows = []
    for path in sorted(RELEASES.glob("*.tsv")):
        for line in path.read_text().splitlines():
            if not line.strip():
                continue
            cols = line.split("\t")
            if len(cols) != 6:
                raise SystemExit(f"{path}: expected 6 columns, found {len(cols)}")
            artifact, version, tag, asset, sha256, length = cols
            rows.append(
                {
                    "artifact": artifact,
                    "version": version,
                    "tag": tag,
                    "asset": asset,
                    "sha256": sha256,
                    "length": int(length),
                }
            )
    rows.sort(key=lambda r: (r["artifact"], semver(r["version"])))
    return rows


def load_annotations():
    with open(ANNOTATIONS, "rb") as f:
        return tomllib.load(f)


def source_version(artifact):
    crate = CRATES.get(artifact)
    if crate is None:
        return None
    manifest = ROOT / crate / "Cargo.toml"
    if not manifest.is_file():
        return None
    match = re.search(r'^version\s*=\s*"([^"]+)"', manifest.read_text(), re.MULTILINE)
    return match.group(1) if match else None


def table(headers, rows):
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    out.extend("| " + " | ".join(r) + " |" for r in rows)
    return "\n".join(out)


def generate(rows, annotations):
    blocks = [
        BEGIN,
        "",
        "<!-- Generated by script/docs/gen-release-log.py from contract/artifacts/releases/*.tsv and script/docs/release-annotations.toml. Do not edit by hand; run `just docs-generate`. -->",
        "",
        "### Newest Release per Artifact\n",
    ]
    summary = []
    for artifact in sorted({r["artifact"] for r in rows}):
        newest = max((r for r in rows if r["artifact"] == artifact), key=lambda r: semver(r["version"]))
        source = source_version(artifact)
        summary.append(
            [
                f"`{artifact}`",
                DESCRIPTIONS.get(artifact, ""),
                newest["version"],
                source or "n/a",
                str(sum(1 for r in rows if r["artifact"] == artifact)),
            ]
        )
    blocks.append(table(["Artifact", "Contract", "Newest released", "Source version on `dev`", "Releases"], summary))

    blocks.append("\n### Release Catalog\n")
    body = []
    for r in rows:
        key = f"{r['artifact']}@{r['version']}"
        ann = annotations.get(key, {})
        body.append(
            [
                f"`{r['artifact']}`",
                r["version"],
                f"[`{r['tag']}`]({RELEASE_URL}/{r['tag']})",
                f"`{r['asset']}`",
                f"<code>{r['sha256']}</code>",
                f"{r['length']:,}",
                f"`{ann['registry_key']}`" if "registry_key" in ann else INPUT_NEEDED,
                ann.get("audit", INPUT_NEEDED),
                ann.get("note", ""),
            ]
        )
    blocks.append(
        table(
            ["Artifact", "Version", "Release tag", "Asset", "SHA-256", "Bytes", "Registry key", "Audit", "Notes"],
            body,
        )
    )
    blocks.append("")
    blocks.append(END)
    return "\n".join(blocks) + "\n"


def splice(page_text, block):
    start = page_text.find(BEGIN)
    end = page_text.find(END)
    if start < 0 or end < 0 or end < start:
        raise SystemExit(f"{PAGE} is missing the generated-block markers")
    end += len(END) + 1
    return page_text[:start] + block + page_text[end:]


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if the page is stale")
    parser.add_argument("--stdout", action="store_true", help="print the block instead of writing")
    args = parser.parse_args()

    rows = load_rows()
    annotations = load_annotations()
    unknown = set(annotations) - {f"{r['artifact']}@{r['version']}" for r in rows}
    if unknown:
        raise SystemExit(f"annotations for rows not in the catalog: {sorted(unknown)}")

    block = generate(rows, annotations)
    if args.stdout:
        sys.stdout.write(block)
        return 0

    current = PAGE.read_text()
    updated = splice(current, block)
    if args.check:
        if updated == current:
            return 0
        sys.stdout.writelines(
            difflib.unified_diff(
                current.splitlines(keepends=True),
                updated.splitlines(keepends=True),
                fromfile=str(PAGE.relative_to(ROOT)),
                tofile="generated",
            )
        )
        print(f"\n{PAGE.relative_to(ROOT)} is stale; run `just docs-generate`.", file=sys.stderr)
        return 1
    if updated != current:
        PAGE.write_text(updated)
        print(f"updated {PAGE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
