[book]
title = "Templar Protocol Guide"
description = "User guide to Templar Protocol smart contract ecosystem"
authors = ["peer2 <peer2@templarprotocol.com>"]
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/Templar-Protocol/contracts/"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/Templar-Protocol/contracts/edit/dev/docs/{path}"
site-url = "/guide/"
