services:
  postgres:
    image: postgres:17.6
    restart: always
    environment:
      POSTGRES_USER: relayeruser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: relayer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  relayer:
    image: rust:1.86.0
    volumes:
      - ../..:/usr/src/relayer
      - rustup_home:/usr/local/rustup
      - cargo_home:/usr/local/cargo
    working_dir: /usr/src/relayer
    command: cargo run --package templar-relayer --profile dev
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://relayeruser:password@postgres:5432/relayer
    ports:
      - 3000:3000

volumes:
  postgres_data:
  rustup_home:
  cargo_home:
