services:
  relayer:
    build:
      context: ../..
      dockerfile: service/relayer/Dockerfile
    image: templar-relayer:latest
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
