allowed_methods:
  - borrow
  - apply_interest
  - harvest_yield
  - withdraw_static_yield
  - withdraw_collateral
  - create_supply_withdrawal_request
  - cancel_supply_withdrawal_request
  - execute_next_supply_withdrawal_request
  - storage_deposit
  # Don't enable the storage withdrawal methods, because they can be used to easily extract NEAR from the relayer.
  # - storage_unregister
  # - storage_withdraw
starting_allowance_yocto: "250000000000000000000000" # 0.25 NEAR
cache:
  gas_price_secs: 600 # 10 minutes
  nonce_secs: 60 # 1 minute
broom:
  batch_size: 16
  interval_secs: 300 # 5 minutes
