name: Undeploy staging
on:
  pull_request:
    types: [closed]

jobs:
  cleanup-staging:
    name: Cleanup staging account
    runs-on: ubuntu-latest
    env:
      NEAR_CONTRACT_PR_STAGING_ACCOUNT_ID: gh-${{ github.event.number }}.${{ vars.NEAR_CONTRACT_STAGING_ACCOUNT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install near CLI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/near-cli-rs/releases/download/v0.19.0/near-cli-rs-installer.sh | sh
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.85.0
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Remove markets
        run: |
          ./script/ci/remove-all-markets-from-registry.sh \
            --account     "${{ env.NEAR_CONTRACT_PR_STAGING_ACCOUNT_ID }}" \
            --registry    "${{ env.NEAR_CONTRACT_PR_STAGING_ACCOUNT_ID }}" \
            --network     "${{ vars.NEAR_CONTRACT_STAGING_NETWORK }}" \
            --private-key "${{ secrets.NEAR_CONTRACT_STAGING_ACCOUNT_PRIVATE_KEY }}" \
            --public-key  "${{ vars.NEAR_CONTRACT_STAGING_ACCOUNT_PUBLIC_KEY }}"

      - name: Remove registry account
        run: |
          ./script/ci/remove-registry.sh \
            --account     "${{ env.NEAR_CONTRACT_PR_STAGING_ACCOUNT_ID }}" \
            --beneficiary "${{ vars.NEAR_CONTRACT_STAGING_ACCOUNT_ID }}" \
            --network     "${{ vars.NEAR_CONTRACT_STAGING_NETWORK }}" \
            --private-key "${{ secrets.NEAR_CONTRACT_STAGING_ACCOUNT_PRIVATE_KEY }}" \
            --public-key  "${{ vars.NEAR_CONTRACT_STAGING_ACCOUNT_PUBLIC_KEY }}"
